/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/building.glb
Author: Daniyal Malik (https://sketchfab.com/daniyalmalik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-building1-721f78c9869647f1877e501983ce9fef
Title: Lowpoly Building1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('/building.glb')
  return (
    <group {...props} dispose={null} position={[100,14,0]} >
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export function Model3(props) {
  const { nodes, materials } = useGLTF('/building.glb')
  return (
    <group {...props} dispose={null} position={[-10,15,15]} >
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}
export function Model4(props) {
  const { nodes, materials } = useGLTF('/building.glb')
  return (
    <group {...props} dispose={null} position={[-100,9,-15]} rotation-y={Math.PI*0.5 } >
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}
useGLTF.preload('/building.glb')


