/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/lowpoly-map.glb
Author: Space_One (https://sketchfab.com/aslbekburonbey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-fps-tdm-game-map-d41a19f699ea421a9aa32b407cb7537b
Title: LOWPOLY | FPS | TDM | GAME | MAP
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lowpoly-map.glb')
  return (
    <group {...props} castShadow receiveShadow dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.754, 3.087, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Cube005_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.Cube005_1.geometry} material={materials.material_4} />
        </group>
        <group position={[3, 0, 0]}>
          <mesh geometry={nodes.room_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.room_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-2.246, -4.703, 0]}>
          <mesh geometry={nodes.BigBox_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.BigBox_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-1.823, -4.849, 0]}>
          <mesh geometry={nodes.Barrel_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-1.833, -4.578, 0]}>
          <mesh geometry={nodes.BarrelB_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.BarrelB_1.geometry} material={materials.material_4} />
        </group>
        <group position={[2.032, -1.25, 0]}>
          <mesh geometry={nodes.BigBox001_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.BigBox001_1.geometry} material={materials.material_4} />
        </group>
        <group position={[2.032, 1.655, 0]}>
          <mesh geometry={nodes.BigBox002_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.BigBox002_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.899, -3.77, 0]}>
          <mesh geometry={nodes.Barrel001_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel001_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.899, -3.543, 0]}>
          <mesh geometry={nodes.Barrel002_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel002_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.899, -3.655, 0.35]}>
          <mesh geometry={nodes.Barrel003_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel003_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.885, -2.958, 0]}>
          <mesh geometry={nodes.BarrelB001_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.BarrelB001_1.geometry} material={materials.material_4} />
        </group>
        <group position={[2.913, 0, 1]}>
          <mesh geometry={nodes.BigBox003_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.BigBox003_1.geometry} material={materials.material_4} />
        </group>
        <group position={[3.284, -2.424, 0]}>
          <mesh geometry={nodes.BigBox004_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.BigBox004_1.geometry} material={materials.material_4} />
        </group>
        <group position={[2.616, -4.001, 0]}>
          <mesh geometry={nodes.Barrel004_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel004_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.561, -1.117, 0]}>
          <mesh geometry={nodes.Barrel005_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel005_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.825, -7.801, 1.05]}>
          <mesh geometry={nodes.Box008_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box008_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.406, -7.801, 1.05]}>
          <mesh geometry={nodes.Box009_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box009_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.406, -7.37, 1.05]}>
          <mesh geometry={nodes.Box010_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box010_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.634, -7.852, 1.05]}>
          <mesh geometry={nodes.Barrel006_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel006_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.858, -7.85, 1.05]}>
          <mesh geometry={nodes.Barrel007_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel007_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-1.317, -7.85, 1.05]}>
          <mesh geometry={nodes.Barrel008_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel008_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-1.093, -7.852, 1.05]}>
          <mesh geometry={nodes.Barrel009_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel009_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.739, -7.852, 1.401]}>
          <mesh geometry={nodes.Barrel010_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.Barrel010_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.963, -7.85, 1.401]}>
          <mesh geometry={nodes.Barrel011_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.Barrel011_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.818, -7.37, 1.05]}>
          <mesh geometry={nodes.Box011_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box011_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.818, -6.962, 1.05]}>
          <mesh geometry={nodes.Box012_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box012_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.761, -6.355, 1.05]}>
          <mesh geometry={nodes.Barrel012_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel012_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.537, -6.355, 1.05]}>
          <mesh geometry={nodes.Barrel013_0.geometry} material={materials.blue} />
          <mesh geometry={nodes.Barrel013_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.455, -5.869, 0]}>
          <mesh geometry={nodes.BigBox007_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.BigBox007_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-2.043, -7.618, 1.05]}>
          <mesh geometry={nodes.Barrel014_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel014_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.331, 6.268, 1.05]}>
          <mesh geometry={nodes.Barrel015_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel015_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.331, 7.899, 1.05]}>
          <mesh geometry={nodes.Barrel016_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel016_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.559, 7.899, 1.05]}>
          <mesh geometry={nodes.Barrel017_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel017_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.791, 7.899, 1.05]}>
          <mesh geometry={nodes.Barrel018_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel018_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.889, 7.899, 1.05]}>
          <mesh geometry={nodes.Barrel019_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel019_1.geometry} material={materials.material_4} />
        </group>
        <group position={[1.133, 1.131, 1]}>
          <mesh geometry={nodes.BigBox009_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.BigBox009_1.geometry} material={materials.material_4} />
        </group>
        <group position={[3.745, 5.434, 0]}>
          <mesh geometry={nodes.BigBox010_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.BigBox010_1.geometry} material={materials.material_4} />
        </group>
        <group position={[2.393, 0, 1]}>
          <mesh geometry={nodes.BigBox011_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.BigBox011_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.403, 1.281, 1]}>
          <mesh geometry={nodes.Barrel020_0.geometry} material={materials.blue} />
          <mesh geometry={nodes.Barrel020_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.043, -0.686, 1]}>
          <mesh geometry={nodes.Barrel021_0.geometry} material={materials.blue} />
          <mesh geometry={nodes.Barrel021_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.268, -0.686, 1]}>
          <mesh geometry={nodes.Barrel022_0.geometry} material={materials.blue} />
          <mesh geometry={nodes.Barrel022_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.153, -0.686, 1.35]}>
          <mesh geometry={nodes.Barrel023_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel023_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.153, -0.468, 1.35]}>
          <mesh geometry={nodes.Barrel024_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.Barrel024_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.268, -0.468, 1]}>
          <mesh geometry={nodes.Barrel025_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel025_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.043, -0.468, 1]}>
          <mesh geometry={nodes.Barrel026_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel026_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.043, -0.248, 1]}>
          <mesh geometry={nodes.Barrel027_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel027_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.268, -0.248, 1]}>
          <mesh geometry={nodes.Barrel028_0.geometry} material={materials.blue} />
          <mesh geometry={nodes.Barrel028_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.153, -0.248, 1.35]}>
          <mesh geometry={nodes.Barrel029_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.Barrel029_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-2.349, 0.126, 0]}>
          <mesh geometry={nodes.BarrelB002_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.BarrelB002_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.86, -7.852, 0.045]}>
          <mesh geometry={nodes.Barrel030_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel030_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-1.084, -7.85, 0.045]}>
          <mesh geometry={nodes.Barrel031_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel031_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.626, -7.85, 0.045]}>
          <mesh geometry={nodes.Barrel032_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel032_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-0.402, -7.852, 0.045]}>
          <mesh geometry={nodes.Barrel033_0.geometry} material={materials.blue} />
          <mesh geometry={nodes.Barrel033_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-1.23, 6.506, 1.05]}>
          <mesh geometry={nodes.BigBox008_0.geometry} material={materials.material_9} />
          <mesh geometry={nodes.BigBox008_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-2.741, -7.878, 0]}>
          <mesh geometry={nodes.BarrelB003_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.BarrelB003_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-2.475, -7.878, 0]}>
          <mesh geometry={nodes.BarrelB004_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.BarrelB004_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.304, 4.815, 0.045]}>
          <mesh geometry={nodes.Barrel034_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel034_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.876, 3.8, 0.045]}>
          <mesh geometry={nodes.Barrel035_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel035_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.876, 3.561, 0.045]}>
          <mesh geometry={nodes.Barrel036_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel036_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.876, 3.32, 0.045]}>
          <mesh geometry={nodes.Barrel037_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel037_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.876, 3.43, 0.395]}>
          <mesh geometry={nodes.Barrel038_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel038_1.geometry} material={materials.material_4} />
        </group>
        <group position={[-3.876, 3.675, 0.395]}>
          <mesh geometry={nodes.Barrel039_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel039_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.406, -6.351, 1.05]}>
          <mesh geometry={nodes.Box037_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box037_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.406, -6.351, 1.45]}>
          <mesh geometry={nodes.Box038_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box038_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.811, -6.351, 1.45]}>
          <mesh geometry={nodes.Box039_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box039_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.811, -6.351, 1.05]}>
          <mesh geometry={nodes.Box040_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Box040_1.geometry} material={materials.material_4} />
        </group>
        <group position={[0.561, 0.019, 0]}>
          <mesh geometry={nodes.Barrel040_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Barrel040_1.geometry} material={materials.material_4} />
        </group>
        <mesh geometry={nodes.up2_0.geometry} material={materials.material_11} position={[-3.538, -5.424, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.obj000_0.geometry} material={materials.material_3} position={[2.303, -4.17, 0]} />
        <mesh geometry={nodes.floors_0.geometry} material={materials.material_9} />
        <mesh geometry={nodes.Plane_0.geometry} material={materials.plane} />
        <mesh geometry={nodes.Cube_0.geometry} material={materials.material_6} position={[-3.6, -4, 0.5]} />
        <mesh geometry={nodes.obj002_0.geometry} material={materials.material_6} position={[3.641, -3.9, 0.5]} />
        <mesh geometry={nodes.Box_0.geometry} material={materials.material} position={[-2.289, -5.16, 0]} />
        <mesh geometry={nodes.miniBox_0.geometry} material={materials.material} position={[-2.287, -4.814, 0.499]} />
        <mesh geometry={nodes.obj001_0.geometry} material={materials.material} position={[-1.241, -7.812, 0]} />
        <mesh geometry={nodes.obj004_0.geometry} material={materials.material_6} position={[3.641, 5.07, 0.5]} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials.stair} position={[3.79, -1, 0]} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials.stair} position={[3.79, 1, 0]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Box001_0.geometry} material={materials.material} position={[-3.791, -1.7, 0]} />
        <mesh geometry={nodes.Box002_0.geometry} material={materials.material} position={[-3.347, -1.7, 0]} />
        <mesh geometry={nodes.Box003_0.geometry} material={materials.material} position={[-3.681, -1.7, 0.398]} />
        <mesh geometry={nodes.miniBox001_0.geometry} material={materials.material} position={[-3.047, -1.65, 0]} />
        <mesh geometry={nodes.Box004_0.geometry} material={materials.material} position={[-1.799, -0.698, 1]} />
        <mesh geometry={nodes.Box005_0.geometry} material={materials.material} position={[-1.328, 0.985, 1]} />
        <mesh geometry={nodes.Box006_0.geometry} material={materials.material} position={[-1.743, 0.985, 1]} />
        <mesh geometry={nodes.Box007_0.geometry} material={materials.material} position={[-1.945, 1.599, 0]} />
        <mesh geometry={nodes.miniBox002_0.geometry} material={materials.material} position={[-1.633, 1.51, 0]} />
        <mesh geometry={nodes.miniBox003_0.geometry} material={materials.material} position={[-2.041, 1.51, 0.399]} />
        <mesh geometry={nodes.miniBox004_0.geometry} material={materials.material} position={[-1.837, 1.079, 1.4]} />
        <mesh geometry={nodes.miniBox005_0.geometry} material={materials.material} position={[-1.624, 1.079, 1.4]} />
        <mesh geometry={nodes.miniBox006_0.geometry} material={materials.material} position={[-1.418, 1.079, 1.4]} />
        <mesh geometry={nodes.obj005_0.geometry} material={materials.material_3} position={[-1.793, -0.91, 1.167]} rotation={[1.484, 0, 0]} />
        <mesh geometry={nodes.obj007_0.geometry} material={materials.material_3} position={[-0.686, -1.179, 0]} />
        <mesh geometry={nodes.Cube004_0.geometry} material={materials.material_11} position={[0, -7.124, 1]} />
        <mesh geometry={nodes.Cube006_0.geometry} material={materials.material_3} position={[1.33, -3.467, 0]} rotation={[0, 0, -2.491]} />
        <mesh geometry={nodes.Cube007_0.geometry} material={materials.material_3} position={[1.403, 6.49, 0]} rotation={[0, 0, 1.584]} />
        <mesh geometry={nodes.obj011_0.geometry} material={materials.material_3} position={[0.183, -7.289, 1.248]} rotation={[0, -1.42, 0]} />
        <mesh geometry={nodes.obj012_0.geometry} material={materials.material_3} position={[0.73, -7.753, 1.448]} />
        <mesh geometry={nodes.Box013_0.geometry} material={materials.material} position={[2.995, -7.799, 1.05]} />
        <mesh geometry={nodes.Box014_0.geometry} material={materials.material} position={[3.398, -7.799, 1.05]} />
        <mesh geometry={nodes.Box015_0.geometry} material={materials.material} position={[3.797, -7.799, 1.05]} />
        <mesh geometry={nodes.Box016_0.geometry} material={materials.material} position={[3.631, -7.799, 1.45]} />
        <mesh geometry={nodes.miniBox007_0.geometry} material={materials.material} position={[3.329, -7.711, 1.45]} />
        <mesh geometry={nodes.obj018_0.geometry} material={materials.material_3} position={[-0.746, -6.229, 1.248]} rotation={[-1.42, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.obj019_0.geometry} material={materials.material_3} position={[-2.016, 0.449, 1.225]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.obj020_0.geometry} material={materials.material_3} position={[-2.016, 0.449, 1]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.obj021_0.geometry} material={materials.material_3} position={[-2.016, 0.045, 1]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.obj022_0.geometry} material={materials.material_3} position={[-2.016, 0.045, 1.225]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.obj023_0.geometry} material={materials.material_3} position={[-0.685, -3.639, 0]} />
        <mesh geometry={nodes.Cube003_0.geometry} material={materials.material} position={[-3.144, -4.616, 1.029]} rotation={[0, 0, -0.634]} />
        <mesh geometry={nodes.Cube008_0.geometry} material={materials.material} position={[-2.988, -4.587, 1.029]} rotation={[0, 0, -0.634]} />
        <mesh geometry={nodes.Cube009_0.geometry} material={materials.material} position={[-3.093, -4.361, 1.029]} rotation={[0, 0, -0.634]} />
        <mesh geometry={nodes.Cube010_0.geometry} material={materials.material} position={[2.024, -5.922, 0.984]} rotation={[-1.396, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube013_0.geometry} material={materials.material} position={[2.224, -5.922, 0.984]} rotation={[-1.396, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube014_0.geometry} material={materials.material} position={[3.902, -5.042, 1.053]} rotation={[-0.023, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube015_0.geometry} material={materials.material} position={[3.786, -5.042, 1.053]} rotation={[-0.023, 0, Math.PI / 2]} />
        <mesh geometry={nodes.obj024_0.geometry} material={materials.material_6} position={[-2.596, -4.68, 0.5]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Box017_0.geometry} material={materials.material} position={[-0.002, -5.894, 0.398]} />
        <mesh geometry={nodes.Box018_0.geometry} material={materials.material} position={[-0.002, -5.894, 0]} />
        <mesh geometry={nodes.obj025_0.geometry} material={materials.material_3} position={[0.008, -5.512, 0]} />
        <mesh geometry={nodes.miniBox008_0.geometry} material={materials.material} position={[0.095, -5.584, 0.228]} />
        <mesh geometry={nodes.miniBox009_0.geometry} material={materials.material} position={[0.31, -5.999, 0.5]} />
        <mesh geometry={nodes.miniBox010_0.geometry} material={materials.material} position={[-0.099, -5.999, 0.798]} />
        <mesh geometry={nodes.obj026_0.geometry} material={materials.material_3} position={[-2.553, -6.409, 1.05]} />
        <mesh geometry={nodes.Box019_0.geometry} material={materials.material} position={[2.134, -6.731, 1.05]} />
        <mesh geometry={nodes.obj027_0.geometry} material={materials.material_3} position={[2.146, -6.7, 1.448]} />
        <mesh geometry={nodes.Box020_0.geometry} material={materials.material} position={[-1.727, -6.469, 0]} />
        <mesh geometry={nodes.obj028_0.geometry} material={materials.material_6} position={[-3.529, 5.07, 0.5]} />
        <mesh geometry={nodes.Cube016_0.geometry} material={materials.material_11} position={[0, 7.124, 1]} />
        <mesh geometry={nodes.Cube019_0.geometry} material={materials.material} position={[1.495, 7.451, 0.543]} rotation={[0, 0.386, 0]} />
        <mesh geometry={nodes.Box021_0.geometry} material={materials.material} position={[-1.685, 6.38, 1.05]} />
        <mesh geometry={nodes.Box022_0.geometry} material={materials.material} position={[-3.786, 6.38, 1.05]} />
        <mesh geometry={nodes.obj003_0.geometry} material={materials.material_3} position={[-3.376, 6.363, 1.05]} />
        <mesh geometry={nodes.obj029_0.geometry} material={materials.material_3} position={[-3.376, 6.363, 1.275]} />
        <mesh geometry={nodes.Box023_0.geometry} material={materials.material} position={[-1.685, 7.794, 1.05]} />
        <mesh geometry={nodes.miniBox011_0.geometry} material={materials.material} position={[-1.807, 6.356, 1.45]} />
        <mesh geometry={nodes.obj030_0.geometry} material={materials.material_3} position={[-0.007, 7.539, 0]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.obj031_0.geometry} material={materials.material_3} position={[0.402, 6.4, 0]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.obj039_0.geometry} material={materials.material_9} position={[-2.397, -0.231, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube022_0.geometry} material={materials.material} position={[-3.859, 0.099, 0.984]} rotation={[0, 1.449, 0]} />
        <mesh geometry={nodes.Cube023_0.geometry} material={materials.material} position={[-3.804, 0.403, 0.984]} rotation={[0, 1.396, 0]} />
        <mesh geometry={nodes.Cube025_0.geometry} material={materials.material} position={[-3.804, 0.908, 0.952]} rotation={[0.293, 1.396, 0]} />
        <mesh geometry={nodes.Cube026_0.geometry} material={materials.material} position={[-3.954, 0.38, 0.01]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube027_0.geometry} material={materials.material} position={[-3.831, 0.38, 0.01]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube028_0.geometry} material={materials.material} position={[-3.579, 0.38, 0.05]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube030_0.geometry} material={materials.material} position={[-3.805, -0.338, 0.984]} rotation={[0, 1.396, 0]} />
        <mesh geometry={nodes.Cube031_0.geometry} material={materials.material} position={[-3.795, -1.409, 0.984]} rotation={[0, 1.396, 0]} />
        <mesh geometry={nodes.Cube032_0.geometry} material={materials.material} position={[-3.802, -0.475, 0.984]} rotation={[0, 1.396, 0]} />
        <mesh geometry={nodes.obj041_0.geometry} material={materials.material_3} position={[0.693, 1.184, 1]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.obj042_0.geometry} material={materials.material_3} position={[0.689, 1.19, 1.188]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube020_0.geometry} material={materials.material} position={[-0.018, 2.258, 0.935]} rotation={[-0.107, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube021_0.geometry} material={materials.material} position={[-0.203, 2.258, 0.913]} rotation={[-0.13, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube024_0.geometry} material={materials.material} position={[-0.367, 2.258, 0.913]} rotation={[-0.13, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube034_0.geometry} material={materials.material} position={[-0.889, 2.258, 0.913]} rotation={[-0.129, 0.006, 1.527]} />
        <mesh geometry={nodes.Box024_0.geometry} material={materials.material} position={[-0.649, 1.177, 1]} />
        <mesh geometry={nodes.obj048_0.geometry} material={materials.material_6} position={[-0.082, -3.9, 0.5]} />
        <mesh geometry={nodes.obj049_0.geometry} material={materials.material_6} position={[-0.082, 3.9, 0.5]} />
        <mesh geometry={nodes.Cube029_0.geometry} material={materials.barier} position={[-3.695, 2.435, 0]} />
        <mesh geometry={nodes.Cube033_0.geometry} material={materials.barier} position={[-1.77, 2.587, 0]} />
        <mesh geometry={nodes.obj050_0.geometry} material={materials.material_3} position={[-0.685, -1.179, 0.224]} />
        <mesh geometry={nodes.obj051_0.geometry} material={materials.material_3} position={[0.515, 3.648, 0]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Cube035_0.geometry} material={materials.blue} position={[2.054, 3.278, 0]} rotation={[0, 0, 0.621]} />
        <mesh geometry={nodes.Cube036_0.geometry} material={materials.barier} position={[-2.069, -1.284, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Box025_0.geometry} material={materials.material} position={[-1.945, 5.92, 0]} />
        <mesh geometry={nodes.Box026_0.geometry} material={materials.material} position={[-2.36, 5.92, 0]} />
        <mesh geometry={nodes.Box027_0.geometry} material={materials.material} position={[-2.343, 5.92, 0.4]} />
        <mesh geometry={nodes.Box028_0.geometry} material={materials.material} position={[-1.932, 5.887, 0.4]} />
        <mesh geometry={nodes.Box029_0.geometry} material={materials.material} position={[-2.123, 5.496, 0]} />
        <mesh geometry={nodes.obj052_0.geometry} material={materials.material_3} position={[3.771, 7.803, 0]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.obj038_0.geometry} material={materials.material_9} position={[-2.397, -0.231, 0.45]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube011_0.geometry} material={materials.material_8} position={[-1.344, 6.386, 0]} />
        <mesh geometry={nodes.Cube017_0.geometry} material={materials.material_8} position={[3.498, -6.384, 0]} />
        <mesh geometry={nodes.Box030_0.geometry} material={materials.material} position={[-0.406, -6.469, 0]} />
        <mesh geometry={nodes.Box031_0.geometry} material={materials.material} position={[-0.42, -6.469, 0.4]} />
        <mesh geometry={nodes.obj040_0.geometry} material={materials.blue} position={[1.681, -7.79, 0]} />
        <mesh geometry={nodes.obj053_0.geometry} material={materials.material_3} position={[1.284, -7.79, 0]} />
        <mesh geometry={nodes.obj054_0.geometry} material={materials.material} position={[0.882, -7.79, 0]} />
        <mesh geometry={nodes.obj055_0.geometry} material={materials.material_4} position={[0.479, -7.79, 0]} />
        <mesh geometry={nodes.Box032_0.geometry} material={materials.material} position={[-3.799, -7.775, 0]} />
        <mesh geometry={nodes.miniBox012_0.geometry} material={materials.material} position={[-3.886, -7.466, 0]} />
        <mesh geometry={nodes.miniBox013_0.geometry} material={materials.material} position={[-3.886, -7.216, 0]} />
        <mesh geometry={nodes.miniBox014_0.geometry} material={materials.material} position={[-3.886, -6.988, 0]} />
        <mesh geometry={nodes.miniBox015_0.geometry} material={materials.material} position={[-3.886, -6.768, 0]} />
        <mesh geometry={nodes.miniBox016_0.geometry} material={materials.material} position={[-3.886, -6.857, 0.2]} />
        <mesh geometry={nodes.miniBox017_0.geometry} material={materials.material} position={[-3.886, -7.08, 0.2]} />
        <mesh geometry={nodes.miniBox018_0.geometry} material={materials.material} position={[-3.886, -7.309, 0.2]} />
        <mesh geometry={nodes.miniBox019_0.geometry} material={materials.material} position={[-3.886, -7.215, 0.4]} />
        <mesh geometry={nodes.miniBox020_0.geometry} material={materials.material} position={[-3.886, -7.856, 0.4]} />
        <mesh geometry={nodes.miniBox021_0.geometry} material={materials.material} position={[-3.886, -6.24, 0]} />
        <mesh geometry={nodes.obj056_0.geometry} material={materials.material_3} position={[-2.117, -6.748, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.obj057_0.geometry} material={materials.material} position={[-0.835, -7.812, 0]} />
        <mesh geometry={nodes.obj058_0.geometry} material={materials.material} position={[-0.432, -7.812, 0]} />
        <mesh geometry={nodes.obj059_0.geometry} material={materials.material_3} position={[3.082, -6.11, 0.167]} rotation={[-1.42, 0, 0]} />
        <mesh geometry={nodes.obj060_0.geometry} material={materials.material_3} position={[3.452, -6.11, 0.19]} rotation={[-1.42, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.obj061_0.geometry} material={materials.material_3} position={[2.578, -7.825, 0]} />
        <mesh geometry={nodes.obj063_0.geometry} material={materials.material_3} position={[3.798, -7.829, 0.225]} />
        <mesh geometry={nodes.obj062_0.geometry} material={materials.material_3} position={[3.392, -7.829, 0.225]} />
        <mesh geometry={nodes.Box033_0.geometry} material={materials.material} position={[3.754, -6.898, 0]} />
        <mesh geometry={nodes.Box034_0.geometry} material={materials.material} position={[1.696, -6.342, 0]} />
        <mesh geometry={nodes.Box035_0.geometry} material={materials.material} position={[-3.762, 4.72, 0]} />
        <mesh geometry={nodes.obj064_0.geometry} material={materials.material} position={[-3.309, 4.792, 0]} />
        <mesh geometry={nodes.Box036_0.geometry} material={materials.material} position={[-3.759, 4.758, 0.48]} />
        <mesh geometry={nodes.obj065_0.geometry} material={materials.material} position={[-3.814, 3.778, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.obj066_0.geometry} material={materials.material} position={[-3.814, 3.371, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Box041_0.geometry} material={materials.material} position={[-0.828, -6.469, 0.4]} />
        <mesh geometry={nodes.Box042_0.geometry} material={materials.material} position={[-0.813, -6.469, 0]} />
        <mesh geometry={nodes.Box043_0.geometry} material={materials.material} position={[-1.742, -6.469, 0.4]} />
        <mesh geometry={nodes.Box044_0.geometry} material={materials.material} position={[1.696, -5.055, 0]} />
        <mesh geometry={nodes.Box045_0.geometry} material={materials.material} position={[2.172, -5.055, 0]} />
        <mesh geometry={nodes.Box046_0.geometry} material={materials.Point} position={[3.429, -5.075, 0]} />
        <mesh geometry={nodes.Box047_0.geometry} material={materials.material} position={[1.748, 0.959, 0]} />
        <mesh geometry={nodes.miniBox022_0.geometry} material={materials.material} position={[-1.895, 1.079, 0.4]} />
        <mesh geometry={nodes.Box048_0.geometry} material={materials.material} position={[-1.804, 0.985, 0]} />
        <mesh geometry={nodes.Box049_0.geometry} material={materials.material} position={[-1.804, -0.605, 0]} />
        <mesh geometry={nodes.miniBox023_0.geometry} material={materials.material} position={[-1.895, -0.307, 0]} />
        <mesh geometry={nodes.Box050_0.geometry} material={materials.material} position={[-0.607, -0.605, 0]} />
        <mesh geometry={nodes.Box051_0.geometry} material={materials['3.010']} position={[-0.192, 0.998, 0]} />
        <mesh geometry={nodes.Box052_0.geometry} material={materials.material} position={[-1.735, -6.335, 1.05]} />
        <mesh geometry={nodes.Box053_0.geometry} material={materials.material} position={[-1.735, -6.335, 1.45]} />
        <mesh geometry={nodes.Box054_0.geometry} material={materials.material} position={[2.534, -6.336, 1.05]} />
        <mesh geometry={nodes.Box055_0.geometry} material={materials.material} position={[2.534, -6.336, 1.45]} />
        <mesh geometry={nodes.Box056_0.geometry} material={materials['3.015']} position={[2.172, -5.055, 0.48]} />
        <mesh geometry={nodes.Box057_0.geometry} material={materials.material} position={[-0.002, -2.946, 0]} />
        <mesh geometry={nodes.Box058_0.geometry} material={materials.material} position={[-0.002, -2.946, 0.398]} />
        <mesh geometry={nodes.Box059_0.geometry} material={materials.material} position={[-0.002, -2.545, 0.398]} />
        <mesh geometry={nodes.Box060_0.geometry} material={materials.material} position={[-0.002, -2.545, 0]} />
        <mesh geometry={nodes.Box061_0.geometry} material={materials.material} position={[-0.939, 0.163, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/lowpoly-map.glb')
