/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/skyrim.glb
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/map-of-skyrim-2d0c053e71574731b424a55fbaa068e1
Title: Map of Skyrim
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/skyrim.glb')
  return (
    <group {...props} dispose={null} scale={0.2} rotation-x={-0.2}>
      <group position={[0, -22.4, 52.428]} rotation={[-2.953, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-12.409, 351.513, -0.1]}>
            <mesh geometry={nodes['Map_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            <mesh geometry={nodes['Map_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
            <mesh geometry={nodes['Map_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
            <mesh geometry={nodes['Map_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/skyrim.glb')
